[package]
name = "edict2"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
lazy_static = "1.4.0"
ouroboros = "0.18.1"
regex = { version = "1.10.2", default-features = false, features = ["std", "perf"] }
