#!/usr/bin/env bash
# Usage: copy this file to .git/hooks/

# Exit at first error
set -Eeu

# To handle partially committed files, we must copy the staged changes to a
# separate location
# See also https://stackoverflow.com/a/36793330
TEMPDIR=$(mktemp -d)
trap 'rm -rf "$TEMPDIR"' EXIT SIGHUP SIGINT SIGQUIT SIGTERM
git checkout-index --prefix="$TEMPDIR/" -af

# keep using the same target/ directory, not a new one in the temporary
# directory this avoids re-parsing everything from scratch every time we run
# the script
GIT_ROOT=$(git rev-parse --show-toplevel)

# lint Python
if ! git diff --cached --name-only --diff-filter=AM --quiet -- nhkeasier; then
    pushd $TEMPDIR >/dev/null
    cat >nhkeasier/secrets.py <<EOF
SECRET_KEY = ''
EMAIL_HOST_PASSWORD = ''
EOF
    ruff check
    mypy --strict .
    popd >/dev/null
fi

# lint Rust: edict2
if ! git diff --cached --name-only --diff-filter=AM --quiet -- edict2; then
    pushd $TEMPDIR/edict2 >/dev/null
    export CARGO_TARGET_DIR="${GIT_ROOT}/edict2/target"
    echo "Running cargo fmt"
    cargo fmt --check
    echo "Running cargo clippy"
    cargo clippy --all -- --deny warnings
    popd >/dev/null
fi

# lint Rust nhkeasier-rs
if ! git diff --cached --name-only --diff-filter=AM --quiet -- nhkeasier-rs; then
    pushd $TEMPDIR/nhkeasier-rs >/dev/null
    export CARGO_TARGET_DIR="${GIT_ROOT}/nhkeasier-rs/target"
    echo "Running cargo fmt"
    cargo fmt --check
    echo "Running cargo clippy"
    cargo clippy --all -- --deny warnings
    popd >/dev/null
fi
