# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('published', models.DateTimeField()),
                ('title_with_ruby', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('raw_content', models.TextField()),
                ('content_with_ruby', models.TextField()),
                ('content', models.TextField()),
                ('story_url', models.URLField()),
                ('image_url', models.URLField(null=True)),
                ('voice_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
