# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import nhkstories.models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_url',
        ),
        migrations.RemoveField(
            model_name='story',
            name='voice_url',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.FileField(null=True, upload_to=nhkstories.models.NameByStoryID('jpg')),
        ),
        migrations.AddField(
            model_name='story',
            name='voice',
            field=models.FileField(null=True, upload_to=nhkstories.models.NameByStoryID('mp3')),
        ),
        migrations.AddField(
            model_name='story',
            name='webpage',
            field=models.FileField(null=True, upload_to=nhkstories.models.NameByStoryID('html')),
        ),
    ]
