# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='r_nhkeasynews_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
