# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-05 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0002_auto_20180205_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='raw_content',
        ),
    ]
