# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import nhkstories.models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0003_remove_story_raw_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(null=True, upload_to=nhkstories.models.NameByStoryID('mp4')),
        ),
    ]
