# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0004_story_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_with_ruby',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title_with_ruby',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
