# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0005_auto_20180206_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
