# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 18:14
from __future__ import unicode_literals

from django.db import migrations


def increment_id(apps, schema_editor):
    Story = apps.get_model('nhkstories', 'Story')
    for i, story in enumerate(Story.objects.all().order_by('published')):
        story.id = i + 1
        story.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0006_story_id'),
    ]

    operations = [
        migrations.RunPython(increment_id),
    ]
