# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0007_auto_20180206_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.CharField(max_length=200),
        ),
    ]
