# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import nhkstories.models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0008_auto_20180206_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(null=True, upload_to=nhkstories.models.video_original_filename),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(null=True, upload_to=nhkstories.models.image_filename),
        ),
        migrations.AlterField(
            model_name='story',
            name='voice',
            field=models.FileField(null=True, upload_to=nhkstories.models.voice_filename),
        ),
        migrations.AlterField(
            model_name='story',
            name='webpage',
            field=models.FileField(null=True, upload_to=nhkstories.models.webpage_filename),
        ),
    ]
