# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import nhkstories.models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0009_auto_20180206_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='video',
            new_name='video_original',
        ),
        migrations.AddField(
            model_name='story',
            name='video_reencoded',
            field=models.FileField(null=True, upload_to=nhkstories.models.video_reencoded_filename),
        ),
    ]
