# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 09:03
from __future__ import unicode_literals
import os
import tempfile
import subprocess

from django.db import migrations
from django.core.files import File


def reencode_videos(apps, schema_editor):
    Story = apps.get_model('nhkstories', 'Story')
    for story in Story.objects.all():
        if not story.video_original:
            story.video_reencoded = File(None)
            story.save()
            continue

        print('Converting %s' % story.video_original.name)
        _, temp_name = tempfile.mkstemp(suffix='.mp4')
        subprocess.run(
            ['ffmpeg', '-y', '-i', story.video_original.file.name, '-b:v', '500k', temp_name],
            stderr=subprocess.DEVNULL, check=True
        )
        with open(temp_name, 'rb') as f:
            story.video_reencoded.save('', f)
        os.remove(temp_name)


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0010_auto_20180206_2056'),
    ]

    operations = [
        migrations.RunPython(reencode_videos),
    ]
