# Generated by Django 2.0.2 on 2018-02-15 15:12

import glob
import subprocess

from django.db import migrations


def make_progressive(apps, schema_editor):
    files = glob.glob('media/**/*.jpg', recursive=True)
    subprocess.run(['mogrify', '-interlace', 'plane'] + files, check=True)


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0011_auto_20180207_1703'),
    ]

    operations = [
        migrations.RunPython(make_progressive),
    ]
