# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-25 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0012_auto_20180215_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='subedict_created',
            field=models.BooleanField(default=False),
        ),
    ]
