# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:16
from __future__ import unicode_literals
import os

from django.db import migrations
from django.conf import settings

from nhkstories.edict.subedict import create_subedict, create_subenamdict, save_subedict


def update_subedicts(apps, schema_editor):
    Story = apps.get_model('nhkstories', 'Story')
    stories = Story.objects.all()

    # ensure the directories exist
    subedict_dir = os.path.join(settings.BASE_DIR, 'media', 'subedict')
    subenamdict_dir = os.path.join(settings.BASE_DIR, 'media', 'subenamdict')
    os.makedirs(subedict_dir, exist_ok=True)
    os.makedirs(subenamdict_dir, exist_ok=True)

    # create sub EDICT files for stories and list days that must be updated
    days = set()
    for story in stories:
        days.add(story.published.date())
        # create sub EDICT files for story
        subedict = create_subedict(story.content)
        subenamdict = create_subenamdict(story.content)
        filename = '{:05}.dat'.format(story.id)
        save_subedict(subedict, os.path.join(subedict_dir, filename))
        save_subedict(subenamdict, os.path.join(subenamdict_dir, filename))
        print(filename)
    print('Story-wise sub EDICT files updated')

    # update sub EDICT files for days
    for day in sorted(days):
        # aggregate stories of the day
        day_stories = Story.objects.filter(published__date=day)
        text = ''.join(story.content for story in day_stories)
        # update sub EDICT files for day
        subedict = create_subedict(text)
        subenamdict = create_subenamdict(text)
        filename = '{}.dat'.format(day)
        save_subedict(subedict, os.path.join(subedict_dir, filename))
        save_subedict(subenamdict, os.path.join(subenamdict_dir, filename))
        print(filename)
    print('Day-wise sub EDICT files updated')

    # note that the subedict have been generated for those stories
    stories.update(subedict_created=True)

class Migration(migrations.Migration):

    dependencies = [
        ('nhkstories', '0013_story_subedict_created'),
    ]

    operations = [
        migrations.RunPython(update_subedicts),
    ]
