# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-25 08:27
from __future__ import unicode_literals

import os
import json
import tempfile
import subprocess
from urllib.request import urlopen, HTTPError

from django.db import migrations

BASE_URL = 'http://www3.nhk.or.jp/news/easy/'
replace_voice_url = BASE_URL + 'player/voice_replace/voice_replace.json'
fragmented_voice_url_pattern = 'https://nhks-vh.akamaihd.net/i/news/easy/{voice_id}.mp4/master.m3u8'


def update_voice(story, voice_id):
    # fragmented MP4 using HTTP Live Streaming
    voice_url = fragmented_voice_url_pattern.format(voice_id=voice_id)
    _, temp_name = tempfile.mkstemp(suffix='.mp3')
    res = subprocess.run(['ffmpeg', '-y', '-i', voice_url, temp_name],
                         stderr=subprocess.DEVNULL)
    if res.returncode == 0:
        story.voice.delete()
        with open(temp_name, 'rb') as f:
            story.voice.save('', f)
        story.save()
    os.remove(temp_name)


def update_voices(apps, schema_editor):
    Story = apps.get_model('nhkstories', 'Story')

    with urlopen(replace_voice_url) as f:
        data = f.read()
    amendments = json.loads(data.decode())

    for amendment in amendments:
        story = Story.objects.get(story_id=amendment['news_id'])
        voice_id = amendment['voice_id']
        update_voice(story, voice_id)


class Migration(migrations.Migration):
    dependencies = [
        ('nhkstories', '0014_update_subedict'),
    ]

    operations = [
        migrations.RunPython(update_voices),
    ]
