# Generated by Django 1.11.16 on 2018-11-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models

from ..models import (
    image_filename, video_original_filename, video_reencoded_filename,
    voice_filename, webpage_filename,
)


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=200)),
                ('published', models.DateTimeField(null=True)),
                ('title_with_ruby', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content_with_ruby', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('webpage', models.FileField(null=True, upload_to=webpage_filename)),
                ('image', models.FileField(null=True, upload_to=image_filename)),
                ('voice', models.FileField(null=True, upload_to=voice_filename)),
                ('video_original', models.FileField(null=True, upload_to=video_original_filename)),
                ('video_reencoded', models.FileField(null=True, upload_to=video_reencoded_filename)),
                ('subedict_created', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
