# Generated by Django 1.11.18 on 2019-02-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0002_story_r_nhkeasynews_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='twitter_post_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
