# Generated by Django 1.11.18 on 2019-02-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0003_story_twitter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='facebook_post_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
