# Generated by Django 4.2 on 2023-12-14 20:07

from django.db import migrations, models

import nhkeasier.models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0004_story_facebook_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_with_ruby',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='title_with_ruby',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='webpage',
            field=models.FileField(upload_to=nhkeasier.models.webpage_filename),
        ),
    ]
