# Generated by Django 4.2 on 2023-12-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0005_alter_story_content_alter_story_content_with_ruby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='facebook_post_id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='r_nhkeasynews_link',
        ),
        migrations.RemoveField(
            model_name='story',
            name='twitter_post_id',
        ),
    ]
