# Generated by Django 4.2 on 2023-12-20 16:54

from django.db import migrations, models

import nhkeasier.models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0006_remove_story_facebook_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_with_ruby',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title_with_ruby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='webpage',
            field=models.FileField(null=True, upload_to=nhkeasier.models.webpage_filename),
        ),
    ]
