# Generated by Django 4.2 on 2023-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0007_alter_story_content_alter_story_content_with_ruby_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['story_id'], name='nhkeasier_s_story_i_fbe045_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['published'], name='nhkeasier_s_publish_295bcd_idx'),
        ),
    ]
