# Generated by Django 4.2 on 2023-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhkeasier', '0008_story_nhkeasier_s_story_i_fbe045_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='title_with_ruby',
            field=models.CharField(max_length=200),
        ),
    ]
